print("📝 My Slam Book Entry")

name = input("Enter your name: Abdullah ")
nickname = input("Enter your nickname:ABD ")
best_friends = input("Enter your best friends names:Hashir and hashim ")
hobbies = input("Enter your hobbies: playing cricket,coding  ")
favorite_subject = input("Enter your favorite subject:Math and Computer ")
funny_memory = input("Share one funny memory:I shouted the wrong answer in class with full confidence — everyone laughed, even the teacher! 😂 ")
unforgettable_moment = input("Share something you'll never forget: I will never forget that one time poakistan vs india match at 2024 india won and i come school next day and i teasing that pakistan loss and in few seconds i jumped on my friend hashim at assembly. ")
recent_event = input("Share something you did recently:Some boys were teasing me and trying to make fun of me in front of others. I felt really upset. At first, I reacted in anger and we got into a fight. ")
message_for_friends = input("Write a message for your friends: Always stay honest, be kind to others, and never let small fights break your friendship. Real friends forgive and grow together.")

print("\n--- Your Slam Book Entry ---\n")
print(f"Name: {name}")
print(f"Nickname: {nickname}")
print(f"Best Friends’ Names: {best_friends}")
print(f"Hobbies: {hobbies}") 
print(f"Favorite Subject: {favorite_subject}")
print(f"One Funny Memory: {funny_memory}")
print(f"Something I’ll Never Forget: {unforgettable_moment}")
print(f"Something I Did Recently: {recent_event}")
print(f"My Message for Friends: {message_for_friends}")
